version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "github*"
          - "go.uber*"
          - "golang*"
          - "gopkg.*"
          - "k8s.*"
          - "kubevirt.*"
          - "sigs.k8s*"
