version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      github-dependencies:
        patterns:
          - "github*"
      golang-dependencies:
        patterns:
          - "golang*"
      k8s-dependencies:
        patterns:
          - "k8s.*"
          - "sigs.k8s*"
      misc-dependencies:
        patterns:
          - "go.uber*"
          - "gopkg.*"
          - "gotest*"
          - "honnef*"
          - "kubevirt.*"