/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1beta1 "github.com/openshift/hypershift/api/hypershift/v1beta1"
	hypershiftv1beta1 "github.com/openshift/hypershift/client/applyconfiguration/hypershift/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHostedControlPlanes implements HostedControlPlaneInterface
type FakeHostedControlPlanes struct {
	Fake *FakeHypershiftV1beta1
	ns   string
}

var hostedcontrolplanesResource = v1beta1.SchemeGroupVersion.WithResource("hostedcontrolplanes")

var hostedcontrolplanesKind = v1beta1.SchemeGroupVersion.WithKind("HostedControlPlane")

// Get takes name of the hostedControlPlane, and returns the corresponding hostedControlPlane object, and an error if there is any.
func (c *FakeHostedControlPlanes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.HostedControlPlane, err error) {
	emptyResult := &v1beta1.HostedControlPlane{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(hostedcontrolplanesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.HostedControlPlane), err
}

// List takes label and field selectors, and returns the list of HostedControlPlanes that match those selectors.
func (c *FakeHostedControlPlanes) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.HostedControlPlaneList, err error) {
	emptyResult := &v1beta1.HostedControlPlaneList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(hostedcontrolplanesResource, hostedcontrolplanesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.HostedControlPlaneList{ListMeta: obj.(*v1beta1.HostedControlPlaneList).ListMeta}
	for _, item := range obj.(*v1beta1.HostedControlPlaneList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hostedControlPlanes.
func (c *FakeHostedControlPlanes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(hostedcontrolplanesResource, c.ns, opts))

}

// Create takes the representation of a hostedControlPlane and creates it.  Returns the server's representation of the hostedControlPlane, and an error, if there is any.
func (c *FakeHostedControlPlanes) Create(ctx context.Context, hostedControlPlane *v1beta1.HostedControlPlane, opts v1.CreateOptions) (result *v1beta1.HostedControlPlane, err error) {
	emptyResult := &v1beta1.HostedControlPlane{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(hostedcontrolplanesResource, c.ns, hostedControlPlane, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.HostedControlPlane), err
}

// Update takes the representation of a hostedControlPlane and updates it. Returns the server's representation of the hostedControlPlane, and an error, if there is any.
func (c *FakeHostedControlPlanes) Update(ctx context.Context, hostedControlPlane *v1beta1.HostedControlPlane, opts v1.UpdateOptions) (result *v1beta1.HostedControlPlane, err error) {
	emptyResult := &v1beta1.HostedControlPlane{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(hostedcontrolplanesResource, c.ns, hostedControlPlane, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.HostedControlPlane), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHostedControlPlanes) UpdateStatus(ctx context.Context, hostedControlPlane *v1beta1.HostedControlPlane, opts v1.UpdateOptions) (result *v1beta1.HostedControlPlane, err error) {
	emptyResult := &v1beta1.HostedControlPlane{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(hostedcontrolplanesResource, "status", c.ns, hostedControlPlane, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.HostedControlPlane), err
}

// Delete takes name of the hostedControlPlane and deletes it. Returns an error if one occurs.
func (c *FakeHostedControlPlanes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(hostedcontrolplanesResource, c.ns, name, opts), &v1beta1.HostedControlPlane{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHostedControlPlanes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(hostedcontrolplanesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.HostedControlPlaneList{})
	return err
}

// Patch applies the patch and returns the patched hostedControlPlane.
func (c *FakeHostedControlPlanes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.HostedControlPlane, err error) {
	emptyResult := &v1beta1.HostedControlPlane{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(hostedcontrolplanesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.HostedControlPlane), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied hostedControlPlane.
func (c *FakeHostedControlPlanes) Apply(ctx context.Context, hostedControlPlane *hypershiftv1beta1.HostedControlPlaneApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.HostedControlPlane, err error) {
	if hostedControlPlane == nil {
		return nil, fmt.Errorf("hostedControlPlane provided to Apply must not be nil")
	}
	data, err := json.Marshal(hostedControlPlane)
	if err != nil {
		return nil, err
	}
	name := hostedControlPlane.Name
	if name == nil {
		return nil, fmt.Errorf("hostedControlPlane.Name must be provided to Apply")
	}
	emptyResult := &v1beta1.HostedControlPlane{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(hostedcontrolplanesResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.HostedControlPlane), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeHostedControlPlanes) ApplyStatus(ctx context.Context, hostedControlPlane *hypershiftv1beta1.HostedControlPlaneApplyConfiguration, opts v1.ApplyOptions) (result *v1beta1.HostedControlPlane, err error) {
	if hostedControlPlane == nil {
		return nil, fmt.Errorf("hostedControlPlane provided to Apply must not be nil")
	}
	data, err := json.Marshal(hostedControlPlane)
	if err != nil {
		return nil, err
	}
	name := hostedControlPlane.Name
	if name == nil {
		return nil, fmt.Errorf("hostedControlPlane.Name must be provided to Apply")
	}
	emptyResult := &v1beta1.HostedControlPlane{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(hostedcontrolplanesResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions(), "status"), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.HostedControlPlane), err
}
