name: unit-test
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write
jobs:
  unit-test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5.3.0
        with:
          go-version-file: go.mod
          cache: false
      - name: Run unit tests
        run: go test -race -parallel=$(nproc) -count=1 -timeout=15m -coverprofile cover.out -covermode=atomic -coverpkg=./... ./...
      - name: Codecov
        uses: codecov/codecov-action@v5.4.0
        with:
          files: ./cover.out
          token: ${{ secrets.CODECOV_TOKEN }}
          