name: Determine unit test coverage
on: 
  workflow_run:
    workflows: [unit-test]
    types:
      - completed

jobs:
  determine-ut-coverage:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: cover.out
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: 'Comment on PR'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
              const issue_number = context.payload.workflow_run.pull_requests[0].number;
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: 'Everything is OK. Thank you for the PR!'
              });
